; Proyecto: Control automatizado de tinaco — Loop Nopal Solutions
; Placa: ESP32-C3 Supermini

upload_port = COM5
monitor_port = COM5
monitor_speed = 115200

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino


; El ESP32-C3 Supermini usa el puerto USB nativo del chip (no un chip
; serie externo), así que estas dos banderas son necesarias para que
; el Serial Monitor funcione correctamente.
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
